/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_ComBCD2_H_
#define	_ComBCD2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OctetString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ComBCD2 */
typedef OctetString_t	 ComBCD2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ComBCD2;
asn_struct_free_f ComBCD2_free;
asn_struct_print_f ComBCD2_print;
asn_constr_check_f ComBCD2_constraint;
ber_type_decoder_f ComBCD2_decode_ber;
der_type_encoder_f ComBCD2_encode_der;
xer_type_decoder_f ComBCD2_decode_xer;
xer_type_encoder_f ComBCD2_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ComBCD2_H_ */
#include <asn_internal.h>
