/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#include "CSD.h"

static asn_TYPE_member_t asn_MBR_CSD_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSD, choice.oad),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"oad"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSD, choice.road),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ROAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"road"
		},
};
static asn_TYPE_tag2member_t asn_MAP_CSD_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* oad */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* road */
};
static asn_CHOICE_specifics_t asn_SPC_CSD_specs_1 = {
	sizeof(struct CSD),
	offsetof(struct CSD, _asn_ctx),
	offsetof(struct CSD, present),
	sizeof(((struct CSD *)0)->present),
	asn_MAP_CSD_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CSD = {
	"CSD",
	"CSD",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CSD_1,
	2,	/* Elements count */
	&asn_SPC_CSD_specs_1	/* Additional specs */
};

