/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_DateTimeBCDH_H_
#define	_DateTimeBCDH_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTimeBCD.h"
#include "LongUnsigned.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DateTimeBCDH */
typedef struct DateTimeBCDH {
	DateTimeBCD_t	 dateTime;
	LongUnsigned_t	 milliSec;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DateTimeBCDH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DateTimeBCDH;

#ifdef __cplusplus
}
#endif

#endif	/* _DateTimeBCDH_H_ */
#include <asn_internal.h>
