/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#include "DateTime.h"

static asn_TYPE_member_t asn_MBR_DateTime_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, year),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"year"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, month),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"month"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, dayOfMonth),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dayOfMonth"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, dayOfWeek),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dayOfWeek"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, hour),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hour"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, minute),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"minute"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, second),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"second"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DateTime, milliseconds),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"milliseconds"
		},
};
static ber_tlv_tag_t asn_DEF_DateTime_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DateTime_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 7 }, /* year */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, -1, 6 }, /* month */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, -2, 5 }, /* dayOfMonth */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, -3, 4 }, /* dayOfWeek */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 4, -4, 3 }, /* hour */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 5, -5, 2 }, /* minute */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 6, -6, 1 }, /* second */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 7, -7, 0 } /* milliseconds */
};
static asn_SEQUENCE_specifics_t asn_SPC_DateTime_specs_1 = {
	sizeof(struct DateTime),
	offsetof(struct DateTime, _asn_ctx),
	asn_MAP_DateTime_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DateTime = {
	"DateTime",
	"DateTime",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DateTime_tags_1,
	sizeof(asn_DEF_DateTime_tags_1)
		/sizeof(asn_DEF_DateTime_tags_1[0]), /* 1 */
	asn_DEF_DateTime_tags_1,	/* Same as above */
	sizeof(asn_DEF_DateTime_tags_1)
		/sizeof(asn_DEF_DateTime_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DateTime_1,
	8,	/* Elements count */
	&asn_SPC_DateTime_specs_1	/* Additional specs */
};

