/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_DoubleLongUnsigned_H_
#define	_DoubleLongUnsigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Integer32.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DoubleLongUnsigned */
typedef Integer32_t	 DoubleLongUnsigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DoubleLongUnsigned;
asn_struct_free_f DoubleLongUnsigned_free;
asn_struct_print_f DoubleLongUnsigned_print;
asn_constr_check_f DoubleLongUnsigned_constraint;
ber_type_decoder_f DoubleLongUnsigned_decode_ber;
der_type_encoder_f DoubleLongUnsigned_encode_der;
xer_type_decoder_f DoubleLongUnsigned_decode_xer;
xer_type_encoder_f DoubleLongUnsigned_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DoubleLongUnsigned_H_ */
#include <asn_internal.h>
