/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_Float64_H_
#define	_Float64_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OctetString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Float64 */
typedef OctetString_t	 Float64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Float64;
asn_struct_free_f Float64_free;
asn_struct_print_f Float64_print;
asn_constr_check_f Float64_constraint;
ber_type_decoder_f Float64_decode_ber;
der_type_encoder_f Float64_encode_der;
xer_type_decoder_f Float64_decode_xer;
xer_type_encoder_f Float64_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Float64_H_ */
#include <asn_internal.h>
