/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_Integer_H_
#define	_Integer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Integer */
typedef BIT_STRING_t	 Integer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Integer;
asn_struct_free_f Integer_free;
asn_struct_print_f Integer_print;
asn_constr_check_f Integer_constraint;
ber_type_decoder_f Integer_decode_ber;
der_type_encoder_f Integer_encode_der;
xer_type_decoder_f Integer_decode_xer;
xer_type_encoder_f Integer_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Integer_H_ */
#include <asn_internal.h>
