/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_Integer32_H_
#define	_Integer32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Integer32 */
typedef long	 Integer32_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Integer32;
asn_struct_free_f Integer32_free;
asn_struct_print_f Integer32_print;
asn_constr_check_f Integer32_constraint;
ber_type_decoder_f Integer32_decode_ber;
der_type_encoder_f Integer32_encode_der;
xer_type_decoder_f Integer32_decode_xer;
xer_type_encoder_f Integer32_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Integer32_H_ */
#include <asn_internal.h>
