/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_Long_H_
#define	_Long_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Long */
typedef BIT_STRING_t	 Long_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Long;
asn_struct_free_f Long_free;
asn_struct_print_f Long_print;
asn_constr_check_f Long_constraint;
ber_type_decoder_f Long_decode_ber;
der_type_encoder_f Long_encode_der;
xer_type_decoder_f Long_decode_xer;
xer_type_encoder_f Long_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Long_H_ */
#include <asn_internal.h>
