ASN_MODULE_SOURCES=	\
	Null.c	\
	Array.c	\
	Structure.c	\
	Bool.c	\
	BitString.c	\
	Integer32.c	\
	Integer8.c	\
	DoubleLong.c	\
	DoubleLongUnsigned.c	\
	OctetString.c	\
	Integer.c	\
	Long.c	\
	Unsigned.c	\
	LongUnsigned.c	\
	Long64.c	\
	Long64Unsigned.c	\
	Enum.c	\
	Float32.c	\
	Float64.c	\
	ComBCD2.c	\
	ComBCD4.c	\
	ComBCD6.c	\
	ComBCD8.c	\
	DateTime.c	\
	Date.c	\
	Time.c	\
	DateTimeBCD.c	\
	DateTimeBCDH.c	\
	DateTimeBCDS.c	\
	DateBCD.c	\
	TimeBCD.c	\
	PIID.c	\
	PIID-ACD.c	\
	OI.c	\
	OAD.c	\
	ROAD.c	\
	DAR.c	\
	OMD.c	\
	TI.c	\
	TSA.c	\
	MAC.c	\
	RN.c	\
	CSD.c	\
	RCSD.c	\
	Region.c	\
	PhysicalUnit.c	\
	ScalerUnit.c	\
	RSD.c	\
	Selector1.c	\
	Selector2.c	\
	Selector3.c	\
	Selector4.c	\
	Selector5.c	\
	Selector6.c	\
	Selector7.c	\
	Selector8.c	\
	Selector9.c	\
	Selector10.c	\
	MS.c	\
	SID.c	\
	SIDMAC.c	\
	BaudRate.c	\
	Parity.c	\
	DataBits.c	\
	StopBits.c	\
	FlowCtl.c	\
	COMDCB.c	\
	Data.c

ASN_MODULE_HEADERS=	\
	Null.h	\
	Array.h	\
	Structure.h	\
	Bool.h	\
	BitString.h	\
	Integer32.h	\
	Integer8.h	\
	DoubleLong.h	\
	DoubleLongUnsigned.h	\
	OctetString.h	\
	Integer.h	\
	Long.h	\
	Unsigned.h	\
	LongUnsigned.h	\
	Long64.h	\
	Long64Unsigned.h	\
	Enum.h	\
	Float32.h	\
	Float64.h	\
	ComBCD2.h	\
	ComBCD4.h	\
	ComBCD6.h	\
	ComBCD8.h	\
	DateTime.h	\
	Date.h	\
	Time.h	\
	DateTimeBCD.h	\
	DateTimeBCDH.h	\
	DateTimeBCDS.h	\
	DateBCD.h	\
	TimeBCD.h	\
	PIID.h	\
	PIID-ACD.h	\
	OI.h	\
	OAD.h	\
	ROAD.h	\
	DAR.h	\
	OMD.h	\
	TI.h	\
	TSA.h	\
	MAC.h	\
	RN.h	\
	CSD.h	\
	RCSD.h	\
	Region.h	\
	PhysicalUnit.h	\
	ScalerUnit.h	\
	RSD.h	\
	Selector1.h	\
	Selector2.h	\
	Selector3.h	\
	Selector4.h	\
	Selector5.h	\
	Selector6.h	\
	Selector7.h	\
	Selector8.h	\
	Selector9.h	\
	Selector10.h	\
	MS.h	\
	SID.h	\
	SIDMAC.h	\
	BaudRate.h	\
	Parity.h	\
	DataBits.h	\
	StopBits.h	\
	FlowCtl.h	\
	COMDCB.h	\
	Data.h

ASN_MODULE_HEADERS+=UTF8String.h
ASN_MODULE_HEADERS+=BOOLEAN.h
ASN_MODULE_SOURCES+=BOOLEAN.c
ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_HEADERS+=NativeEnumerated.h
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NULL.h
ASN_MODULE_SOURCES+=NULL.c
ASN_MODULE_SOURCES+=NativeEnumerated.c
ASN_MODULE_HEADERS+=NativeInteger.h
ASN_MODULE_SOURCES+=NativeInteger.c
ASN_MODULE_SOURCES+=UTF8String.c
ASN_MODULE_HEADERS+=VisibleString.h
ASN_MODULE_SOURCES+=VisibleString.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c
ASN_MODULE_HEADERS+=per_support.h
ASN_MODULE_SOURCES+=per_support.c
ASN_MODULE_HEADERS+=per_decoder.h
ASN_MODULE_SOURCES+=per_decoder.c
ASN_MODULE_HEADERS+=per_encoder.h
ASN_MODULE_SOURCES+=per_encoder.c
ASN_MODULE_HEADERS+=per_opentype.h
ASN_MODULE_SOURCES+=per_opentype.c
ASN_CONVERTER_SOURCES+=converter-sample.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = progname
CFLAGS += -I.
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	asn1c test.asn1

