/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_Null_H_
#define	_Null_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Null */
typedef NULL_t	 Null_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Null;
asn_struct_free_f Null_free;
asn_struct_print_f Null_print;
asn_constr_check_f Null_constraint;
ber_type_decoder_f Null_decode_ber;
der_type_encoder_f Null_encode_der;
xer_type_decoder_f Null_decode_xer;
xer_type_encoder_f Null_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Null_H_ */
#include <asn_internal.h>
