/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_OMD_H_
#define	_OMD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OI.h"
#include "Integer8.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OMD */
typedef struct OMD {
	OI_t	 objId;
	Integer8_t	 methodId;
	Integer8_t	 actionMode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OMD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OMD;

#ifdef __cplusplus
}
#endif

#endif	/* _OMD_H_ */
#include <asn_internal.h>
