/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_PIID_ACD_H_
#define	_PIID_ACD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PIID-ACD */
typedef BIT_STRING_t	 PIID_ACD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PIID_ACD;
asn_struct_free_f PIID_ACD_free;
asn_struct_print_f PIID_ACD_print;
asn_constr_check_f PIID_ACD_constraint;
ber_type_decoder_f PIID_ACD_decode_ber;
der_type_encoder_f PIID_ACD_encode_der;
xer_type_decoder_f PIID_ACD_decode_xer;
xer_type_encoder_f PIID_ACD_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PIID_ACD_H_ */
#include <asn_internal.h>
