/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_RN_H_
#define	_RN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OctetString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RN */
typedef OctetString_t	 RN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RN;
asn_struct_free_f RN_free;
asn_struct_print_f RN_print;
asn_constr_check_f RN_constraint;
ber_type_decoder_f RN_decode_ber;
der_type_encoder_f RN_encode_der;
xer_type_decoder_f RN_decode_xer;
xer_type_encoder_f RN_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RN_H_ */
#include <asn_internal.h>
