/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#include "ROAD.h"

static asn_TYPE_member_t asn_MBR_ralateObjDescr_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_ralateObjDescr_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ralateObjDescr_specs_3 = {
	sizeof(struct ralateObjDescr),
	offsetof(struct ralateObjDescr, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ralateObjDescr_3 = {
	"ralateObjDescr",
	"ralateObjDescr",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ralateObjDescr_tags_3,
	sizeof(asn_DEF_ralateObjDescr_tags_3)
		/sizeof(asn_DEF_ralateObjDescr_tags_3[0]), /* 1 */
	asn_DEF_ralateObjDescr_tags_3,	/* Same as above */
	sizeof(asn_DEF_ralateObjDescr_tags_3)
		/sizeof(asn_DEF_ralateObjDescr_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ralateObjDescr_3,
	1,	/* Single element */
	&asn_SPC_ralateObjDescr_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ROAD_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ROAD, objDescr),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objDescr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ROAD, ralateObjDescr),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ralateObjDescr_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ralateObjDescr"
		},
};
static ber_tlv_tag_t asn_DEF_ROAD_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ROAD_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* objDescr */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* ralateObjDescr */
};
static asn_SEQUENCE_specifics_t asn_SPC_ROAD_specs_1 = {
	sizeof(struct ROAD),
	offsetof(struct ROAD, _asn_ctx),
	asn_MAP_ROAD_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ROAD = {
	"ROAD",
	"ROAD",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ROAD_tags_1,
	sizeof(asn_DEF_ROAD_tags_1)
		/sizeof(asn_DEF_ROAD_tags_1[0]), /* 1 */
	asn_DEF_ROAD_tags_1,	/* Same as above */
	sizeof(asn_DEF_ROAD_tags_1)
		/sizeof(asn_DEF_ROAD_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ROAD_1,
	2,	/* Elements count */
	&asn_SPC_ROAD_specs_1	/* Additional specs */
};

