/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_ROAD_H_
#define	_ROAD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OAD.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OAD;

/* ROAD */
typedef struct ROAD {
	OAD_t	 objDescr;
	struct ralateObjDescr {
		A_SEQUENCE_OF(struct OAD) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ralateObjDescr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ROAD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ROAD;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OAD.h"

#endif	/* _ROAD_H_ */
#include <asn_internal.h>
