/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_SIDMAC_H_
#define	_SIDMAC_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SID.h"
#include "MAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIDMAC */
typedef struct SIDMAC {
	SID_t	 saftyId;
	MAC_t	 dataMAC;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIDMAC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIDMAC;

#ifdef __cplusplus
}
#endif

#endif	/* _SIDMAC_H_ */
#include <asn_internal.h>
