/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#ifndef	_TimeBCD_H_
#define	_TimeBCD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ComBCD2.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeBCD */
typedef struct TimeBCD {
	ComBCD2_t	 hour;
	ComBCD2_t	 minute;
	ComBCD2_t	 sec;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeBCD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeBCD;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeBCD_H_ */
#include <asn_internal.h>
