/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "test.asn1"
 */

#include "TimeBCD.h"

static asn_TYPE_member_t asn_MBR_TimeBCD_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimeBCD, hour),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ComBCD2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hour"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeBCD, minute),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ComBCD2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"minute"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeBCD, sec),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ComBCD2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sec"
		},
};
static ber_tlv_tag_t asn_DEF_TimeBCD_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TimeBCD_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 2 }, /* hour */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 1 }, /* minute */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -2, 0 } /* sec */
};
static asn_SEQUENCE_specifics_t asn_SPC_TimeBCD_specs_1 = {
	sizeof(struct TimeBCD),
	offsetof(struct TimeBCD, _asn_ctx),
	asn_MAP_TimeBCD_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TimeBCD = {
	"TimeBCD",
	"TimeBCD",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TimeBCD_tags_1,
	sizeof(asn_DEF_TimeBCD_tags_1)
		/sizeof(asn_DEF_TimeBCD_tags_1[0]), /* 1 */
	asn_DEF_TimeBCD_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimeBCD_tags_1)
		/sizeof(asn_DEF_TimeBCD_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TimeBCD_1,
	3,	/* Elements count */
	&asn_SPC_TimeBCD_specs_1	/* Additional specs */
};

